name: Doctors - CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'doctors/**'
  pull_request:
    paths:
      - 'doctors/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
         
      - name: Build
        run: docker build -t moizmazhar47/doctors:${{ github.sha }} ./doctors
       
      - name: Push
        run: docker push moizmazhar47/doctors:${{ github.sha }}

      - name: Update Image on Docker Compose
        run: |
          sed -i "s|image: username/doctors:[0-9a-f]\+|image: username/doctors:${{ github.sha }}|" docker-compose.yml
     
      - name: Check Changes
        run: |
          git diff
          git status
     
      - name: Commit and Push Changes
        run: |
           git config --global user.email "moeez.ch3737@gmail.com"
           git config --global user.name "moizmazhar37"
           git config --local user.password "${{ secrets.GH_TOKEN }}"
         
           # Check if there are changes to commit
           if [ -n "$(git status --porcelain)" ]; then
           git add .
           git commit -m "Update docker-compose.yml"
           git push origin main
           else
            echo "No changes to commit."
           fi
